apiVersion: v1
kind: Secret
metadata:
  name: server
type: Opaque
data:
  DATABASE_USER: {{ getenv "DATABASE_USER" "baselayer" | base64.Encode }}
  DATABASE_PASSWORD: {{ getenv "DATABASE_PASSWORD" "baselayer" | base64.Encode }}
  PRIVATE_KEY_BASE64: {{ .Env.PRIVATE_KEY_BASE64 | base64.Encode }}
  MAILER_USER: {{ .Env.MAILER_USER | base64.Encode }}
  MAILER_PASSWORD: {{ .Env.MAILER_PASSWORD | base64.Encode }}
