apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_USER: {{ getenv "DATABASE_USER" "baselayer" | base64.Encode }}
  POSTGRES_PASSWORD: {{ getenv "DATABASE_PASSWORD" "baselayer" | base64.Encode }}
